sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    mySprite2.destroy(effects.warmRadial, 500)
    info.changeScoreBy(1)
})
let mySprite2: Sprite = null
let mySprite = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . 3 3 3 3 2 4 4 4 . . . 
    . . . . 3 3 3 2 2 2 3 3 4 . . . 
    . . . 3 3 3 2 2 2 6 6 6 4 . . . 
    . . 3 3 3 2 2 6 6 a a a 4 . . . 
    . . 3 3 3 2 6 6 a a a a 3 . . . 
    . . . 3 3 6 6 a a 4 3 3 . . . . 
    . . . . 3 3 3 3 3 3 3 . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(mySprite, 80, 80)
mySprite.setFlag(SpriteFlag.StayInScreen, true)
scene.setBackgroundColor(10)
info.setScore(0)
info.startCountdown(10)
game.onUpdateInterval(2000, function () {
    mySprite2 = sprites.create(img`
        ....ffffff..............
        ..ffeeeef2f.............
        .ffeeeef222f............
        .feeeffeeeef............
        .ffffee2222ef...........
        .fe222ffffe2f...........
        fffffffeeefff...........
        ffe44ebf44eef...........
        fee4d41fddef............
        .feee4ddddf.............
        ..fdde444ef.............
        ..fdde22ccc.............
        ...eef22cdc.............
        ...f4444cddc............
        ....fffffcddc...........
        .....fff..cddc..........
        ...........cdc..........
        ............cc..........
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    mySprite2.setPosition(randint(0, 160), randint(0, 120))
    timer.after(1500, function () {
        mySprite2.destroy(effects.warmRadial, 500)
    })
})
